---
- name: install dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - git
      - python3-pip
      - python3-venv
      - python3-docker
- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
- name: install docker
  apt:
    pkg:
     - docker-ce
     - docker-ce-cli
     - containerd.io
     - docker-buildx-plugin 
     - docker-compose-plugin
     - docker-compose